### ISSUE TITLE
Lesson release checklist

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/r-novice-gapminder-es#55]
## Lesson Release checklist

**For each lesson release, copy this checklist to an issue and check off
during preparation for release**

Scheduled Freeze Date:   2018-04-27
Scheduled Release Date:  2018-04-30  

Checklist of tasks to complete before release:

- [x] check that the learning objectives reflect the content of the lessons
- [x] check that learning objectives are phrased as statements using action words
- [x] check for typos
- [x] check that the live coding examples work as expected
- [x] if example code generates warnings, explain in narrative and instructor notes
- [x] check that challenges and their solutions work as expected
- [x] check that the challenges test skills that have been seen
- [x] check that the setup instructions are up to date (e.g., update version numbers)
- [x] check that data is available and mentions of the data in the lessons are accurate
- [x] check that the instructor guide is up to date with the content of the lessons
- [x] check that all the links within the lessons work (this should be automated)
- [x] check that the cheat sheets included in lessons are up to date (e.g., RStudio updates them regularly)
- [x] check that languge is clear and free of idioms and colloquialisms
- [x] make sure formatting of the code in the lesson looks good (e.g. line breaks)
- [x] check for clarity and flow of narrative
- [x] update README as needed
- [x] fill out “overview” for each module - minutes needed for teaching and exercises, questions and learning objectives
- [x] check that contributor guidelines are clear and consistent
- [x] clean up files (e.g. delete deprecated files, insure filenames are consistent)
- [x] update the release notes (NEWS)
- [ ] tag release on GitHub

**Comment by raynamharris** [comment]
Revised contributing guildlines in https://github.com/swcarpentry/r-novice-gapminder-es/commit/99ef12860a8711f83a21066409da22482eac803b

**Comment by raynamharris** [comment]
Revised README in https://github.com/swcarpentry/r-novice-gapminder-es/commit/469519748bcad8040a231b7b29f2dffc9e16305a

**Comment by raynamharris** [comment]
instructor guide translated!! in https://github.com/swcarpentry/r-novice-gapminder-es/commit/b4235e206aa9536dd09713b83953247683534be4

**Comment by orchid00** [comment]
:grinning:

**Comment by raynamharris** [comment]
@ErinBecker @fmichonneau we are good to go for release

**Comment by fmichonneau** [comment]
lesson released: https://zenodo.org/record/1251333 :tada:
